import { TUser } from '../../user/types/user.type';
import { TColor } from '../../shared/types/colors.type';
import { TProjectCategory } from './projectCategory.type';
import { TProjectSubCategory } from './projectSubCategory.type';
import { TStatus } from './status.type';
import { TTask } from './task.type';
import { TFeature } from './features.type';
import { TRequeriment } from './requeriments.type';

export type TProject = {
  _id: string;
  owners: TUser[];
  name: string;
  description: string;
  category: TProjectCategory;
  subCategory: TProjectSubCategory;
  startDate: Date;
  endDate: Date | undefined;
  features: TFeature[];
  requeriments: TRequeriment[];
  approximateTimeProjection: number;
  status: TStatus;
  lastCheckStatus: Date;
  tasks: TTask[];
  priority: number;
  impact: number;
  impactDescription: string;
  createdAt: Date;
  updatedAt: Date;
} & TColor;
