services:      
  sokoke_planner-prod:
    build: 
      context: .
      target: build
    container_name: sokoke_planner
    ports:
      - "4200:80"
    profiles: ["build"]
  sokoke_planner-dev:
    build: 
      context: .
      target: dev
    container_name: sokoke_planner-dev
    ports:
      - "4200:4200"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: sh -c "ng serve --host 0.0.0.0 --poll=1000"
    profiles: ["dev"]